import type { Metadata } from "next";
import "./globals.css";

import { BookmarkIcon } from "@heroicons/react/20/solid";
import { FilmIcon } from "@heroicons/react/24/outline";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="grid grid-cols-10">
        <nav className="p-6 bg-slate-900 col-span-full flex justify-between items-center">
          <FilmIcon className="size-8" />
          <BookmarkIcon className="size-8" />
        </nav>
        {children}
      </body>
    </html>
  );
}
